alias: Fan mode cancel
description: ""
triggers:
  - trigger: state
    entity_id:
      - climate.sensi_sensi_279414
    attribute: fan_mode
    to: "on"
conditions: []
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - action: climate.set_fan_mode
    metadata: {}
    data:
      fan_mode: auto
    target:
      entity_id: climate.sensi_sensi_279414
  - action: notify.mobile_app_matthews_iphone_2
    metadata: {}
    data:
      message: Fan Mode was set to “On” I have returned it to “Auto”
mode: single
