alias: Reset Temperature Notification
description: ""
triggers:
  - trigger: time
    at: "15:00:00"
conditions: []
actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.temperature_notification_sent
mode: single
